"""added contracts

Revision ID: 01a4b14bf9e6
Revises: 182718a0a9ae
Create Date: 2020-11-29 15:27:56.714402

"""
from alembic import op
import sqlalchemy as sa
import gino.dialects.asyncpg


# revision identifiers, used by Alembic.
revision = '01a4b14bf9e6'
down_revision = '182718a0a9ae'
branch_labels = None
depends_on = None

contact_statuses = gino.dialects.asyncpg.AsyncEnum(
    'NOT_STARTED', 'OPERATING', 'CANCELLED', 'DONE', name='contractstatus'
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'contracts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('number', sa.String(length=40), nullable=False),
        sa.Column('status', contact_statuses, nullable=False),
        sa.Column('path', sa.String(length=120), nullable=False),
        sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
        sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
        sa.Column('provider_id', sa.Integer(), nullable=False),
        sa.Column('cancel_description', sa.String(length=400), nullable=False),
        sa.ForeignKeyConstraint(tuple(['provider_id']), ['providers.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contracts')
    contact_statuses.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
