"""removed user_x_branch

Revision ID: 182718a0a9ae
Revises: f7f61b0fadff
Create Date: 2020-11-26 02:10:39.739942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '182718a0a9ae'
down_revision = 'f7f61b0fadff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_x_branch')
    op.add_column(
        'users', sa.Column('branch_id', sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        'fk_users_branches',
        'users', 'branches',
        ['branch_id'],
        ['id']
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_branches', 'users', type_='foreignkey')
    op.drop_column('users', 'branch_id')
    op.create_table(
        'user_x_branch',
        sa.Column(
            'user_id', sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            'branch_id', sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            tuple(['branch_id']),
            ['branches.id'],
            name='user_x_branch_branch_id_fkey')
        ,
        sa.ForeignKeyConstraint(
            tuple(['user_id']),
            ['users.id'],
            name='user_x_branch_user_id_fkey'
        )
    )
    # ### end Alembic commands ###
