""" Products & Sales

Revision ID: 2c5aac614e6f
Revises: 7292deb23125
Create Date: 2020-11-13 23:11:13.151377

"""
from datetime import datetime

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c5aac614e6f'
down_revision = '7292deb23125'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    t_products = op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('image_path', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=400), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_path'),
    sa.UniqueConstraint('name')
    )
    t_sales = op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    connection = op.get_bind()

    connection.execute(
        sa.insert(t_products).values([
            {'name': 'Красная роза', 'price': 50.7, 'description': 'Красивая очень', 'image_path': 'none1'},
            {'name': 'Лилия', 'price': 25, 'description': 'Бери, не пожалеешь', 'image_path': 'none2'},
            {'name': 'Ромашка', 'price': 5, 'description': 'Одно из наиболее известных лекарственных растений',
             'image_path': 'none3'},
        ])
    )

    connection.execute(
        sa.insert(t_sales).values([
            {
                'value': 10,
                'date': datetime.strptime('10/11/2020 00:00:00', '%d/%m/%Y %H:%M:%S'),
                'product_id': 1,
                'branch_id': 1
            },
            {
                'value': 35000,
                'date': datetime.strptime('11/11/2020 00:00:00', '%d/%m/%Y %H:%M:%S'),
                'product_id': 2,
                'branch_id': 1
            },
            {
                'value': 9,
                'date': datetime.strptime('13/11/2020 00:00:00', '%d/%m/%Y %H:%M:%S'),
                'product_id': 3,
                'branch_id': 2
            },
            {
                'value': 20,
                'date': datetime.strptime('10/09/2020 00:00:00', '%d/%m/%Y %H:%M:%S'),
                'product_id': 1,
                'branch_id': 2
            }
        ])
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales')
    op.drop_table('products')
    # ### end Alembic commands ###
