"""empty message

Revision ID: 7292deb23125
Revises: b3f9310cc0c6
Create Date: 2020-11-08 00:27:30.440779

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '7292deb23125'
down_revision = 'b3f9310cc0c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('address', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('address')
                    )
    op.create_table('user_x_branch',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('branch_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(tuple(['branch_id']), ['branches.id'], ),
                    sa.ForeignKeyConstraint(tuple(['user_id']), ['users.id'], ),
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_x_branch')
    op.drop_table('branches')
    # ### end Alembic commands ###
