"""removed get_one

Revision ID: 89e9565ac244
Revises: e7136da05c80
Create Date: 2021-01-20 20:54:19.277032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89e9565ac244'
down_revision = 'cb5a6b8f52a6'
branch_labels = None
depends_on = None


connection = op.get_bind()

t_permissions = sa.Table(
    'permissions',
    sa.MetaData(),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_name', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        'purchases_address_uq', 'purchases', ['address']
    )

    # ### end Alembic commands ###

    connection.execute(
        sa.insert(t_permissions).values([
            {'app_name': 'supplies', 'action': 'get', 'role_id': 5},
            {'app_name': 'branches', 'action': 'get', 'role_id': 5},
        ])
    )

    connection.execute(
        sa.delete(t_permissions).where(t_permissions.c.action == 'get_one')
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('purchases_address_uq', 'purchases', type_='unique')
    connection.execute(
        sa.delete(t_permissions).where(
            (
                (t_permissions.c.action == 'get')
                & (t_permissions.c.role_id == 5)
                & (
                    (t_permissions.c.app_name == 'supplies')
                    | (t_permissions.c.app_name == 'branches')
                )
            )
        )
    )

    connection.execute(
        sa.insert(t_permissions).values([
            {'app_name': 'supplies', 'action': 'get_one', 'role_id': 1},
            {'app_name': 'supplies', 'action': 'get_one', 'role_id': 2},
            {'app_name': 'supplies', 'action': 'get_one', 'role_id': 4},
            {'app_name': 'supplies', 'action': 'get_one', 'role_id': 5},
            {'app_name': 'supplies', 'action': 'get_one', 'role_id': 6},

            {'app_name': 'branches', 'action': 'get_one', 'role_id': 1},
            {'app_name': 'branches', 'action': 'get_one', 'role_id': 2},
            {'app_name': 'branches', 'action': 'get_one', 'role_id': 3},
            {'app_name': 'branches', 'action': 'get_one', 'role_id': 4},
            {'app_name': 'branches', 'action': 'get_one', 'role_id': 5},
            {'app_name': 'branches', 'action': 'get_one', 'role_id': 6},
        ])
    )
    # ### end Alembic commands ###
