"""empty message

Revision ID: b1a0d6cd7fa7
Revises: b3f9310cc0c6
Create Date: 2020-11-07 16:48:00.478234

"""
from alembic import op
import sqlalchemy as sa
import gino.dialects.asyncpg


# revision identifiers, used by Alembic.
revision = 'b1a0d6cd7fa7'
down_revision = 'b3f9310cc0c6'
branch_labels = None
depends_on = None

provider_status_type = gino.dialects.asyncpg.AsyncEnum(
    'NEW', 'COOPERATE', 'FRAUD', 'STOPPED', name='providerstatustypes'
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    t_providers = op.create_table(
        'providers',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.Column('email', sa.String(length=50), nullable=True),
        sa.Column('phone', sa.String(length=12), nullable=True),
        sa.Column('status', provider_status_type, nullable=False),
        sa.Column('data', sa.String(length=400), nullable=False),
        sa.Column('address', sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###

    connection = op.get_bind()

    connection.execute(
        sa.insert(t_providers).values([
            {
                'id': 1,
                'name': 'DaoFlowers',
                'email': 'dao@daoflowers.com',
                'phone': '+31657713385',
                'status': 'NEW',
                'data': 'Daoflowers — это лучший профессиональный сервис'
                        'в сфере поставок свежесрезанных цветов из Эквадора'
                        ', Колумбии и Кении.',
                'address': 'г. Москва, ул. Пушкина, д. 30'
            },
            {
                'id': 2,
                'name': '7цветов',
                'email': 'dao@daoflowers.com',
                'phone': '88002001711',
                'status': 'COOPERATE',
                'data': 'Мы привозим цветы и растения в горшках из Европы,'
                        ' Эквадора, Колумбии, Кении, Японии, Китая, США и '
                        ' доставляем их свежими во все регионы России.',
                'address': 'г. Москва, ул. Молодогвардейская, д. 61, стр.16'
            },
        ])
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('providers')
    provider_status_type.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
