name: CI

on:
  pull_request:

jobs:
  # This workflow contains a single job called "build"
  check-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest coverage 
        working-directory: "./backend/"
      - name: Lint wiht flake8
        run: |
          flake8
        working-directory: "./backend/"
      - name: Setup postgres
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '13'
      - name: Tests with coverage and pytest
        run: |
          make test-ci
        working-directory: "./backend/"
  check-frontend:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: "12.x"
    - name: npm install, build, and lint
      run: |
        npm ci
        npm run build --if-present
        npm run lint
      env:
        CI: true
      working-directory: "./frontend/"
